import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/app/UI/SideBar";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex relative overflow-hidden">
          <Image
            src="/assets/Group1.svg"
            width={2000}
            height={1000}
            alt="background vector"
            className="absolute top-0 left-0 right-0 bottom-0 z-10"
          />
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
